
const WEBHOOK_TRANSPORT = 'webhook' 
const EMAIL_TRANSPORT = 'email' 
const THEEYE_FILE_TRANSPORT = 'file' 

exports.WEBHOOK_TRANSPORT = WEBHOOK_TRANSPORT
exports.EMAIL_TRANSPORT = EMAIL_TRANSPORT
exports.THEEYE_FILE_TRANSPORT = THEEYE_FILE_TRANSPORT
